version: 1
snapshot:
  percy-css: |
    .percy-timestamp {
      visibility: hidden;
      position: absolute;
    } 
    .percy-timestamp::before {
      content: "July 23, 2023 2:45 PM"; 
      visibility: visible;
      position: relative;
    }