name: Deploy Branch

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm ci --prefer-offline --ignore-scripts

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - run: ./node_modules/.bin/ember deploy --environment=production
        env:
          EMBER_APP_DEPLOY_BRANCH: ${{ steps.branch-name.outputs.current_branch }}
          CDN_BASE_URL: "https://d28fwjy3evlamb.cloudfront.net/"
