name: Publish Sentry Release

on:
  push:
    tags:
      - "v*"

jobs:
  sentry-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: curl -sL https://sentry.io/get-cli/ | bash
      - env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          tag=$(echo $GITHUB_REF | sed "s/refs\\/tags\\///")
          sentry-cli releases -o codecrafters -p frontend new ${tag}
          sentry-cli releases -o codecrafters -p frontend set-commits --auto ${tag} --ignore-missing
