name: Tag

on:
  push:
    branches: [master]

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Ensure that all tags are available

      - name: 'Compute next version number'
        run: |
          currentVersionNumber=$(git tag --list "v*" | sort -V | tail -n 1 | cut -c 2-)
          nextVersionNumber=$(echo $currentVersionNumber + 1 | bc)
          echo "current: $currentVersionNumber"
          echo "next: $nextVersionNumber"
          echo "::set-output name=next_version_number::$nextVersionNumber"
        id: compute_next_version_number

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.compute_next_version_number.outputs.next_version_number }}
